# Generated by Django 5.1.5 on 2025-02-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjsapp', '0002_alter_usercredentials_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
