# Generated by Django 5.1.5 on 2025-02-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cjsapp', '0004_user_delete_usercredentials'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_table',
        ),
    ]
